[package]
name = "font-to-swf"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
swf = { workspace = true }
ttf-parser = "0.25.1"
typed-arena = "2.0.2" # TODO: move to workspace
